/* Generated By:JavaCC: Do not edit this line. Yaka.java */
public class Yaka implements YakaConstants {

        static Expression exp = new Expression();
        static Declaration declaration = new Declaration();
        static TabIdent tabIdent = new TabIdent();
        static YVM yvm = new YVM();
        static YVMasm yvmAsm = new YVMasm();

        static int taille = 0;

        static String typeAffect,typeRetourFct,nomFct;

        static boolean inMain = false;
        static boolean inGlob = false;

        static EtiqUtil ite = new EtiqUtil();
        static EtiqUtil cond = new EtiqUtil();
        static FoncUtil fonc = new FoncUtil();

  public static void main(String args[]) {
    Yaka analyseur;
    java.io.InputStream input;

    if (args.length==1) {
      System.out.print(args[args.length-1] + ": ");
      try {
        input = new java.io.FileInputStream(args[args.length-1]+".yaka");
      } catch (java.io.FileNotFoundException e) {
        System.out.println("Fichier introuvable.");
        return;
      }
    } else if (args.length==0) {
      System.out.println("Lecture sur l'entree standard...");
      input = System.in;
    } else {
      System.out.println("Usage: java Gram [fichier]");
      return;
    }
    try {
      analyseur = new Yaka(input);
      analyseur.analyse();
      System.out.println("analyse syntaxique reussie!");
    } catch (ParseException e) {
      String msg = e.getMessage();
      /*msg = msg.substring(0,msg.indexOf("\n"));*/
      System.out.println("Erreur de syntaxe : "+msg);
    }
  }

/**************************************/
/********debut de la grammaire ********/
/**************************************/
  static final public void analyse() throws ParseException {
    jj_consume_token(PROGRAMME);
    jj_consume_token(ident);
                                yvm.entete(YakaTokenManager.identLu);
                                                        yvmAsm.entete(YakaTokenManager.identLu);
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case BOOLEEN:
      case ENTIER:
        ;
        break;
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      declFonction();
    }
    jj_consume_token(PRINCIPAL);
                inMain = true;
                                        yvm.etiquetteFonc("main");
                                        yvmAsm.etiquetteFonc("main");
    bloc();
    jj_consume_token(FPRINCIPAL);
    jj_consume_token(FPROGRAMME);
                  yvm.queue();
                                  yvmAsm.queue();
  }

  static final public void bloc() throws ParseException {
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case CONST:
        ;
        break;
      default:
        jj_la1[1] = jj_gen;
        break label_2;
      }
      declConst();
    }
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case VAR:
        ;
        break;
      default:
        jj_la1[2] = jj_gen;
        break label_3;
      }
      declVar();
    }
                                        yvm.ouvreBloc(taille);
                                        yvmAsm.ouvreBloc(taille);
    suiteInstr();
  }

  static final public void declConst() throws ParseException {
    jj_consume_token(CONST);
    defConst();
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 40:
        ;
        break;
      default:
        jj_la1[3] = jj_gen;
        break label_4;
      }
      jj_consume_token(40);
      defConst();
    }
    jj_consume_token(41);
  }

  static final public void defConst() throws ParseException {
    jj_consume_token(ident);
           declaration.setSaveName(YakaTokenManager.identLu);
    jj_consume_token(42);
    valConst();
  }

  static final public void valConst() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case entier:
      jj_consume_token(entier);
                                if(tabIdent.existeIdentLoc(declaration.getSaveName())){
                                        System.out.println("Erreur l."+YakaTokenManager.jjFillToken().beginLine+" : La constante "+declaration.getSaveName()+" est deja\u00a0 declaree.");
                                }else{
                                        tabIdent.rangeIdentLoc(declaration.getSaveName(), declaration.createIdentConst("ENTIER", YakaTokenManager.entierLu));
                                }
      break;
    case ident:
      jj_consume_token(ident);
                                if(tabIdent.existeIdentLoc(declaration.getSaveName())){
                                                System.out.println("Erreur l."+YakaTokenManager.jjFillToken().beginLine+" : La variable "+declaration.getSaveName()+" est deja\u00a0 declaree.");
                                }else{
                                        if(tabIdent.existeIdentLoc(YakaTokenManager.identLu)){
                                                tabIdent.rangeIdentLoc(declaration.getSaveName(), tabIdent.chercheIdentGlob(YakaTokenManager.identLu));
                                        }else {
                                                System.out.println("Erreur l."+YakaTokenManager.jjFillToken().beginLine+" : La variable "+YakaTokenManager.identLu+" n'est pas declaree.");
                                        }
                                }
      break;
    case VRAI:
      jj_consume_token(VRAI);
                                if(tabIdent.existeIdentLoc(declaration.getSaveName())){
                                        System.out.println("Erreur l."+YakaTokenManager.jjFillToken().beginLine+" : La variable "+declaration.getSaveName()+" est deja\u00a0 declaree.");
                                }else{
                                        tabIdent.rangeIdentLoc(declaration.getSaveName(), declaration.createIdentConst("BOOLEEN", -1));
                                }
      break;
    case FAUX:
      jj_consume_token(FAUX);
                                if(tabIdent.existeIdentLoc(declaration.getSaveName())){
                                        System.out.println("Erreur l."+YakaTokenManager.jjFillToken().beginLine+" : La variable "+declaration.getSaveName()+" est deja\u00a0 declaree.");
                                }else{
                                        tabIdent.rangeIdentLoc(declaration.getSaveName(), declaration.createIdentConst("BOOLEEN", 0));
                                }
      break;
    default:
      jj_la1[4] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void declVar() throws ParseException {
    jj_consume_token(VAR);
    type();
    jj_consume_token(ident);
                                        if(tabIdent.existeIdentLoc(YakaTokenManager.identLu)){
                                                System.out.println("Erreur l."+YakaTokenManager.jjFillToken().beginLine+" : La variable "+YakaTokenManager.identLu+" est deja\u00a0 declaree.");
                                        }else{
                                                tabIdent.rangeIdentLoc(YakaTokenManager.identLu, declaration.createIdentVar(declaration.getSaveName()));
                                                taille += 2;
                                        }
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 40:
        ;
        break;
      default:
        jj_la1[5] = jj_gen;
        break label_5;
      }
      jj_consume_token(40);
      jj_consume_token(ident);
                                        if(tabIdent.existeIdentLoc(YakaTokenManager.identLu)){
                                                System.out.println("Erreur l."+YakaTokenManager.jjFillToken().beginLine+" : La variable "+YakaTokenManager.identLu+" est deja\u00a0 declaree.");

                                        }else{
                                                tabIdent.rangeIdentLoc(YakaTokenManager.identLu, declaration.createIdentVar(declaration.getSaveName()));
                                                taille +=2;
                                        }
    }
    jj_consume_token(41);
  }

  static final public void type() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ENTIER:
      jj_consume_token(ENTIER);
                 declaration.setSaveName("ENTIER");
      break;
    case BOOLEEN:
      jj_consume_token(BOOLEEN);
                 declaration.setSaveName("BOOLEEN");
      break;
    default:
      jj_la1[6] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

/*
 * Syntaxe des instructions.
 */
  static final public void suiteInstr() throws ParseException {
    instruction();
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 41:
        ;
        break;
      default:
        jj_la1[7] = jj_gen;
        break label_6;
      }
      jj_consume_token(41);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case SI:
      case RETOURNE:
      case TANTQUE:
      case ECRIRE:
      case LIRE:
      case ALALIGNE:
      case ident:
        instruction();
        break;
      default:
        jj_la1[8] = jj_gen;
        ;
      }
    }
  }

  static final public void instruction() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ident:
      affectation();
      break;
    case LIRE:
      lecture();
      break;
    case ECRIRE:
    case ALALIGNE:
      ecriture();
      break;
    case TANTQUE:
      iteration();
      break;
    case SI:
      conditionnelle();
      break;
    case RETOURNE:
      retourne();
      break;
    default:
      jj_la1[9] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void affectation() throws ParseException {
    jj_consume_token(ident);
                                declaration.setSaveName(YakaTokenManager.identLu);
                                if(tabIdent.existeIdentLoc(declaration.getSaveName())){
                                        typeAffect = tabIdent.chercheIdentLoc(declaration.getSaveName()).getType();
                                }else{
                                        System.out.println("Erreur l."+YakaTokenManager.jjFillToken().beginLine+" : La variable "+declaration.getSaveName()+" n'est pas declaree.");
                                }
    jj_consume_token(42);
    expression();
                                                if(tabIdent.existeIdentLoc(declaration.getSaveName())){
                                                        if(tabIdent.chercheIdentLoc(declaration.getSaveName()) instanceof IdVar){
                                                                String popStack = exp.tipToString(exp.peekType());
                                                                if(typeAffect.equals(popStack)){
                                                                        yvm.istore(((IdVar)tabIdent.chercheIdentLoc(declaration.getSaveName())).getOffset());
                                                                        yvmAsm.istore(((IdVar)tabIdent.chercheIdentLoc(declaration.getSaveName())).getOffset());
                                                                }else{
                                                                        System.out.println("Erreur l."+YakaTokenManager.jjFillToken().beginLine+" : Types non egaux. Le type de "+declaration.getSaveName()+" est "+typeAffect
                                                                        +" alors que le type de l'expression est "+popStack+".");
                                                                }
                                                        }else{
                                                                System.out.println("Erreur l."+YakaTokenManager.jjFillToken().beginLine+" : "+declaration.getSaveName()+" est une constante, affectation impossible.");
                                                        }
                                                }
  }

  static final public void lecture() throws ParseException {
    jj_consume_token(LIRE);
    jj_consume_token(43);
    jj_consume_token(ident);
                                                if(tabIdent.existeIdentLoc(YakaTokenManager.identLu)){
                                                        yvm.lireEnt(((IdVar)tabIdent.chercheIdentLoc(YakaTokenManager.identLu)).getOffset());
                                                        yvmAsm.lireEnt(((IdVar)tabIdent.chercheIdentLoc(YakaTokenManager.identLu)).getOffset());
                                                }else{
                                                        System.out.println("Erreur l."+YakaTokenManager.jjFillToken().beginLine+" : La variable "+YakaTokenManager.identLu+" n'est pas declaree.");
                                                }
    jj_consume_token(44);
  }

  static final public void ecriture() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ECRIRE:
      jj_consume_token(ECRIRE);
      jj_consume_token(43);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case VRAI:
      case FAUX:
      case NON:
      case entier:
      case ident:
      case 43:
      case 51:
        expression();
                                                                if("ENTIER".equals(exp.tipToString(exp.peekType()))){
                                                                        yvm.ecrireEnt();
                                                                        yvmAsm.ecrireEnt();
                                                                }else if("BOOLEEN".equals(exp.tipToString(exp.peekType()))){
                                                                        yvm.ecrireBool();
                                                                        yvmAsm.ecrireBool();
                                                                }else System.out.println("Erreur l."+YakaTokenManager.jjFillToken().beginLine+" : Erreur de type dans l'expression entree.");
                                                                exp.popType();
        break;
      case chaine:
        jj_consume_token(chaine);
                                                                yvm.ecrireChaine(YakaTokenManager.chaineLue);
                                                                yvmAsm.ecrireChaine(YakaTokenManager.chaineLue);
        break;
      default:
        jj_la1[10] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(44);
      break;
    case ALALIGNE:
      jj_consume_token(ALALIGNE);
                                                                yvm.aLaLigne();
                                                                yvmAsm.aLaLigne();
      break;
    default:
      jj_la1[11] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void iteration() throws ParseException {
    jj_consume_token(TANTQUE);
                        ite.push();
                                yvm.faire(ite.peek());
                                yvmAsm.faire(ite.peek());
    expression();
                                        if (!(exp.tipToString(exp.popType()).equals("BOOLEEN"))){
                                                System.out.println("Erreur l."+YakaTokenManager.jjFillToken().beginLine+" : Une expression booleenne est attendu.");
                                        }else{
                                                yvm.iffaux("FAIT"+ite.peek());
                                                yvmAsm.iffaux("FAIT"+ite.peek());
                                        }
    jj_consume_token(FAIRE);
    suiteInstr();
    jj_consume_token(FAIT);
                        yvm.jump("FAIRE"+ite.peek());
                        yvmAsm.jump("FAIRE"+ite.peek());
                        yvm.fait(ite.peek());
                        yvmAsm.fait(ite.pop());
  }

  static final public void conditionnelle() throws ParseException {
    jj_consume_token(SI);
    expression();
                                                        if (!(exp.tipToString(exp.popType()).equals("BOOLEEN"))){
                                                                System.out.println("Erreur l."+YakaTokenManager.jjFillToken().beginLine+" : Une expression booleenne est attendu.");
                                                        }

                                                        cond.push();
                                                        yvm.iffaux("SINON"+cond.peek());
                                                        yvmAsm.iffaux("SINON"+cond.peek());
    jj_consume_token(ALORS);
    suiteInstr();
                                                        yvm.jump("FSI"+cond.peek());
                                                        yvmAsm.jump("FSI"+cond.peek());

                                                        yvm.sinon(cond.peek());
                                                        yvmAsm.sinon(cond.peek());
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case SINON:
      jj_consume_token(SINON);
      suiteInstr();
      break;
    default:
      jj_la1[12] = jj_gen;
      ;
    }
    jj_consume_token(FSI);
                        yvm.fsi(cond.peek());
                        yvmAsm.fsi(cond.pop());
  }

/*
 * Expression .
 */
  static final public void expression() throws ParseException {
    simpleExpr();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 42:
    case 45:
    case 46:
    case 47:
    case 48:
    case 49:
      opRel();
      simpleExpr();
                                Expression.Op o = exp.peekOpera();
                                switch(o){
                                        case EGAL :
                                                yvm.iegal();
                                                yvmAsm.iegal();
                                                break;
                                        case DIFF :
                                                yvm.idiff();
                                                yvmAsm.idiff();
                                                break;
                                        case INF :
                                                yvm.iinf();
                                                yvmAsm.iinf();
                                                break;
                                        case INFEGAL :
                                                yvm.iinfegal();
                                                yvmAsm.iinfegal();
                                                break;
                                        case SUP :
                                                yvm.isup();
                                                yvmAsm.isup();
                                                break;
                                        case SUPEGAL :
                                                yvm.isupegal();
                                                yvmAsm.isupegal();
                                                break;
                                        default :
                                }
                                exp.testType2Argv();
      break;
    default:
      jj_la1[13] = jj_gen;
      ;
    }
  }

  static final public void simpleExpr() throws ParseException {
    terme();
    label_7:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case OU:
      case 50:
      case 51:
        ;
        break;
      default:
        jj_la1[14] = jj_gen;
        break label_7;
      }
      opAdd();
      terme();
                        Expression.Op o = exp.peekOpera();
                        switch(o){
                                case PLUS :
                                        yvm.iadd();
                                        yvmAsm.iadd();
                                        break;
                                case MOINS :
                                        yvm.isub();
                                        yvmAsm.isub();
                                        break;
                                case OU :
                                        yvm.ior();
                                        yvmAsm.ior();
                                        break;
                                default :
                        }
                        exp.testType2Argv();
    }
  }

  static final public void terme() throws ParseException {
    facteur();
    label_8:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ET:
      case 52:
      case 53:
        ;
        break;
      default:
        jj_la1[15] = jj_gen;
        break label_8;
      }
      opMul();
      facteur();
                        Expression.Op o = exp.peekOpera();
                        switch(o){
                                case MUL :
                                        yvm.imul();
                                        yvmAsm.imul();
                                        break;
                                case DIV :
                                        yvm.idiv();
                                        yvmAsm.idiv();
                                        break;
                                case ET :
                                        yvm.iand();
                                        yvmAsm.iand();
                                        break;
                                default :
                        }
                        exp.testType2Argv();
    }
  }

  static final public void facteur() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case VRAI:
    case FAUX:
    case entier:
    case ident:
    case 43:
      primaire();
      break;
    case NON:
    case 51:
      opNeg();
      primaire();
                                                Expression.Op o = exp.peekOpera();
                                                switch(o){
                                                        case NON :
                                                                yvm.inot();
                                                                yvmAsm.inot();
                                                                break;
                                                        case MOINS :
                                                                yvm.ineg();
                                                                yvmAsm.ineg();
                                                                break;
                                                        default :
                                                }
                                                exp.testType1Argv();
      break;
    default:
      jj_la1[16] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void primaire() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case VRAI:
    case FAUX:
    case entier:
    case ident:
      valeur();
      break;
    case 43:
      jj_consume_token(43);
      expression();
      jj_consume_token(44);
      break;
    default:
      jj_la1[17] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void valeur() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case entier:
      jj_consume_token(entier);
                                exp.saveType(Expression.Tip.ENTIER);
                                yvm.iconst(YakaTokenManager.entierLu);
                                yvmAsm.iconst(YakaTokenManager.entierLu);
      break;
    case ident:
      jj_consume_token(ident);
                        if (tabIdent.existeIdentGlob(YakaTokenManager.identLu)){
                                        inGlob = true;
                                        fonc.push(YakaTokenManager.identLu);
                                        exp.saveType(exp.stringToTip(tabIdent.chercheIdentGlob(YakaTokenManager.identLu).getType()));
                                        yvm.reserveRetour();
                                        yvmAsm.reserveRetour();
                                }else if(tabIdent.existeIdentLoc(YakaTokenManager.identLu)){
                                        inGlob = false;
                                        exp.saveType(exp.stringToTip(tabIdent.chercheIdentLoc(YakaTokenManager.identLu).getType()));
                                        if(tabIdent.chercheIdentLoc(YakaTokenManager.identLu) instanceof IdConst){
                                                yvm.iconst(((IdConst) tabIdent.chercheIdentLoc(YakaTokenManager.identLu)).getValeur());
                                                yvmAsm.iconst(((IdConst) tabIdent.chercheIdentLoc(YakaTokenManager.identLu)).getValeur());
                                        }else{
                                                yvm.iload(((IdVar) tabIdent.chercheIdentLoc(YakaTokenManager.identLu)).getOffset());
                                                yvmAsm.iload(((IdVar) tabIdent.chercheIdentLoc(YakaTokenManager.identLu)).getOffset());
                                        }
                                }else{
                                        System.out.println("Erreur l."+YakaTokenManager.jjFillToken().beginLine+" : La variable ou la fonction "+YakaTokenManager.identLu+" n'est pas declaree.");
                                }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 43:
        argumentsFonction();
        break;
      default:
        jj_la1[18] = jj_gen;
        ;
      }
      break;
    case VRAI:
      jj_consume_token(VRAI);
                                exp.saveType(Expression.Tip.BOOL);
                                yvm.iconst(-1);
                                yvmAsm.iconst(-1);
      break;
    case FAUX:
      jj_consume_token(FAUX);
                                exp.saveType(Expression.Tip.BOOL);
                                yvm.iconst(0);
                                yvmAsm.iconst(0);
      break;
    default:
      jj_la1[19] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void opRel() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 42:
      jj_consume_token(42);
                 exp.saveOp(Expression.Op.EGAL);
      break;
    case 45:
      jj_consume_token(45);
                 exp.saveOp(Expression.Op.DIFF);
      break;
    case 46:
      jj_consume_token(46);
                 exp.saveOp(Expression.Op.INF);
      break;
    case 47:
      jj_consume_token(47);
                 exp.saveOp(Expression.Op.INFEGAL);
      break;
    case 48:
      jj_consume_token(48);
                 exp.saveOp(Expression.Op.SUP);
      break;
    case 49:
      jj_consume_token(49);
                 exp.saveOp(Expression.Op.SUPEGAL);
      break;
    default:
      jj_la1[20] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void opAdd() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 50:
      jj_consume_token(50);
          exp.saveOp(Expression.Op.PLUS);
      break;
    case 51:
      jj_consume_token(51);
          exp.saveOp(Expression.Op.MOINS);
      break;
    case OU:
      jj_consume_token(OU);
          exp.saveOp(Expression.Op.OU);
      break;
    default:
      jj_la1[21] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void opMul() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 52:
      jj_consume_token(52);
         exp.saveOp(Expression.Op.MUL);
      break;
    case 53:
      jj_consume_token(53);
         exp.saveOp(Expression.Op.DIV);
      break;
    case ET:
      jj_consume_token(ET);
          exp.saveOp(Expression.Op.ET);
      break;
    default:
      jj_la1[22] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void opNeg() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 51:
      jj_consume_token(51);
                 exp.saveOp(Expression.Op.MOINS);
      break;
    case NON:
      jj_consume_token(NON);
                 exp.saveOp(Expression.Op.NON);
      break;
    default:
      jj_la1[23] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void declFonction() throws ParseException {
    type();
                typeRetourFct = declaration.getSaveName();
    jj_consume_token(FONCTION);
    jj_consume_token(ident);
                                if(tabIdent.existeIdentGlob(YakaTokenManager.identLu)){
                                        System.out.println("Erreur l."+YakaTokenManager.jjFillToken().beginLine+" : La fonction "+YakaTokenManager.identLu+" est deja\u00a0 declaree.");
                                }else{
                                        nomFct=YakaTokenManager.identLu;
                                        tabIdent.rangeIdentGlob(nomFct, declaration.createIdentFonc(typeRetourFct));
                                        yvm.etiquetteFonc(nomFct);
                                        yvmAsm.etiquetteFonc(nomFct);
                                }
    paramForms();
    bloc();
    jj_consume_token(FFONCTION);
                int nbParam = ((IdFonc)tabIdent.chercheIdentGlob(nomFct)).getNbParam();
                yvm.fermeBloc(nbParam*2);
                yvmAsm.fermeBloc(nbParam*2);
                tabIdent.clear();
                declaration.clearOffset();
                taille = 0;
  }

  static final public void paramForms() throws ParseException {
    jj_consume_token(43);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case BOOLEEN:
    case ENTIER:
      paramForm();
      label_9:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 40:
          ;
          break;
        default:
          jj_la1[24] = jj_gen;
          break label_9;
        }
        jj_consume_token(40);
        paramForm();
      }
      break;
    default:
      jj_la1[25] = jj_gen;
      ;
    }
    jj_consume_token(44);
          tabIdent.update(((IdFonc)tabIdent.chercheIdentGlob(nomFct)).getNbParam());
  }

  static final public void paramForm() throws ParseException {
    type();
    jj_consume_token(ident);
                                if(tabIdent.existeIdentLoc(YakaTokenManager.identLu)){
                                        System.out.println("Erreur l."+YakaTokenManager.jjFillToken().beginLine+" : La variable "+YakaTokenManager.identLu+" est deja\u00a0 declaree.");
                                }else{
                                        ((IdFonc)tabIdent.chercheIdentGlob(nomFct)).addParam(declaration.getSaveName());
                                        tabIdent.rangeIdentLoc(YakaTokenManager.identLu,
                                                                                   declaration.createIdentVar(declaration.getSaveName(),
                                                                                                                              ((IdFonc)tabIdent.chercheIdentGlob(nomFct)).getNbParam()
                                                                                                                             )
                                                                                  );
                                }
  }

  static final public void retourne() throws ParseException {
    jj_consume_token(RETOURNE);
                                        if (inMain){
                                                System.out.println("Erreur l."+YakaTokenManager.jjFillToken().beginLine+" : Impossible de retourner une valeur dans le programme principal");
                                        }
    expression();
                        if (!inMain){
                                                String save = exp.tipToString(exp.popType());
                                                if(!typeRetourFct.equals(save)){
                                                        System.out.println("Erreur l."+YakaTokenManager.jjFillToken().beginLine+" : La fonction"+nomFct+" retourne un "+typeRetourFct
                                                        +" alors que le type fournis est "+save+".");
                                                }else{
                                                        if(!inMain){
                                                                int nbParam = ((IdFonc)tabIdent.chercheIdentGlob(nomFct)).getNbParam();
                                                                yvm.ireturn((2*(nbParam+2)));
                                                                yvmAsm.ireturn((2*(nbParam+2)));
                                                        }
                                                }
                                        }
  }

  static final public void argumentsFonction() throws ParseException {
    jj_consume_token(43);
                        int nbArg;
                        int total;
                        if(inGlob){
                                nbArg = ((IdFonc)tabIdent.chercheIdentGlob(fonc.peek())).getNbParam();
                                total = nbArg;
                        }else{
                                nbArg = 0;
                                total = nbArg;
                        }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case VRAI:
    case FAUX:
    case NON:
    case entier:
    case ident:
    case 43:
    case 51:
      expression();
                                                if(nbArg > 0 && inGlob){
                                                        String typeArg = ((IdFonc)tabIdent.chercheIdentGlob(fonc.peek())).getParam(total-nbArg);
                                                        if(!typeArg.equals(exp.tipToString(exp.peekType()))){
                                                                int num=total-nbArg + 1;
                                                                System.out.println(     "Erreur l."+YakaTokenManager.jjFillToken().beginLine+
                                                                                                        " : Fonction : "+((IdFonc)tabIdent.chercheIdentGlob(fonc.peek())).affiche(fonc.peek())+", l'argument "+num+" n'est pas du type souhaite. "
                                                                                                        +typeArg+" attendu, "+exp.tipToString(exp.popType())+" recu.");
                                                        }else{
                                                                exp.popType();
                                                        }
                                                }else if(inGlob){
                                                        exp.popType();
                                                }
                                                nbArg--;
      label_10:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 40:
          ;
          break;
        default:
          jj_la1[26] = jj_gen;
          break label_10;
        }
        jj_consume_token(40);
        expression();
                                                                if(nbArg > 0 && inGlob){
                                                                        String typeArg = ((IdFonc)tabIdent.chercheIdentGlob(fonc.peek())).getParam(total-nbArg);
                                                                        if(!typeArg.equals(exp.tipToString(exp.peekType()))){
                                                                                int num=total-nbArg + 1;
                                                                                System.out.println(     "Erreur l."+YakaTokenManager.jjFillToken().beginLine+
                                                                                                                        " : fonction : "+((IdFonc)tabIdent.chercheIdentGlob(fonc.peek())).affiche(fonc.peek())+", l'argument "+num+" n'est pas du type souhaite. "
                                                                                                                        +typeArg+" attendu, "+exp.tipToString(exp.popType())+" recu.");
                                                                        }else{
                                                                                exp.popType();
                                                                        }
                                                                }else if(inGlob){
                                                                        exp.popType();
                                                                }
                                                                nbArg--;
      }
      break;
    default:
      jj_la1[27] = jj_gen;
      ;
    }
    jj_consume_token(44);
                        if(!inGlob && nbArg !=0){
                                System.out.println("Erreur l."+YakaTokenManager.jjFillToken().beginLine+", une variable ne peut accepter des arguments");
                        }else if(nbArg > 0){
                                System.out.println("Erreur l."+YakaTokenManager.jjFillToken().beginLine+" : fonction : "+((IdFonc)tabIdent.chercheIdentGlob(fonc.peek())).affiche(fonc.peek())+" : "+nbArg+" arguments attendus en plus.");
                        }else if(nbArg < 0){
                                System.out.println("Erreur l."+YakaTokenManager.jjFillToken().beginLine+" : fonction : "+((IdFonc)tabIdent.chercheIdentGlob(fonc.peek())).affiche(fonc.peek())+" : "+(-nbArg)+" arguments attendus en moins.");
                        }else{
                                if(!fonc.isEmpty()){
                                        yvm.call(fonc.peek());
                                        yvmAsm.call(fonc.pop());
                                }
                        }
  }

  static private boolean jj_initialized_once = false;
  static public YakaTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  static public Token token, jj_nt;
  static private int jj_ntk;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[28];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_0();
      jj_la1_1();
   }
   private static void jj_la1_0() {
      jj_la1_0 = new int[] {0x8100,0x80000,0x200,0x0,0x120000,0x0,0x8100,0x0,0x52000,0x52000,0x1120000,0x0,0x800,0x0,0x400000,0x800000,0x1120000,0x120000,0x0,0x120000,0x0,0x400000,0x800000,0x1000000,0x0,0x8100,0x0,0x1120000,};
   }
   private static void jj_la1_1() {
      jj_la1_1 = new int[] {0x0,0x0,0x0,0x100,0x50,0x100,0x0,0x200,0x47,0x47,0x808d0,0x5,0x0,0x3e400,0xc0000,0x300000,0x80850,0x850,0x800,0x50,0x3e400,0xc0000,0x300000,0x80000,0x100,0x0,0x100,0x80850,};
   }

  public Yaka(java.io.InputStream stream) {
     this(stream, null);
  }
  public Yaka(java.io.InputStream stream, String encoding) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser.  You must");
      System.out.println("       either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new YakaTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 28; i++) jj_la1[i] = -1;
  }

  static public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  static public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 28; i++) jj_la1[i] = -1;
  }

  public Yaka(java.io.Reader stream) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser.  You must");
      System.out.println("       either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new YakaTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 28; i++) jj_la1[i] = -1;
  }

  static public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 28; i++) jj_la1[i] = -1;
  }

  public Yaka(YakaTokenManager tm) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser.  You must");
      System.out.println("       either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 28; i++) jj_la1[i] = -1;
  }

  public void ReInit(YakaTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 28; i++) jj_la1[i] = -1;
  }

  static final private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

  static final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  static final private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  static private java.util.Vector jj_expentries = new java.util.Vector();
  static private int[] jj_expentry;
  static private int jj_kind = -1;

  static public ParseException generateParseException() {
    jj_expentries.removeAllElements();
    boolean[] la1tokens = new boolean[54];
    for (int i = 0; i < 54; i++) {
      la1tokens[i] = false;
    }
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 28; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 54; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.addElement(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = (int[])jj_expentries.elementAt(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  static final public void enable_tracing() {
  }

  static final public void disable_tracing() {
  }

}
